# Generated by Django 4.2.4 on 2023-10-21 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DOB', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('PREFER NOT TO TELL', 'PREFER NOT TO TELL')], max_length=50)),
                ('phone_number', models.IntegerField(null=True)),
                ('register_number', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('student_profile_setup_verify', models.BooleanField(default=False, help_text='marked as verified, if profile setup is completed')),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_student', to='One.college')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrolled', to='One.course')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileEducator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DOB', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('PREFER NOT TO TELL', 'PREFER NOT TO TELL')], max_length=50)),
                ('phone_number', models.IntegerField(null=True)),
                ('educator_profile_setup_verify', models.BooleanField(default=False, help_text='marked as verified, if profile setup is completed')),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_educator', to='One.college')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_educator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(help_text="don't change starting time while editing, it should be atleast one hour in future to attend the test", null=True)),
                ('year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('submitted_verify', models.BooleanField(default=False, help_text='marked as verified, if all questions are submitted for this quiz (10 questions)')),
                ('publish_verify', models.BooleanField(default=False, help_text='marked as verified, if quiz is published')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_educator', to='One.userprofileeducator')),
                ('student_courses', models.ManyToManyField(blank=True, default='', help_text='quiz will be sent to this dept students', to='One.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionForQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('choice_one', models.CharField(max_length=255)),
                ('choice_two', models.CharField(max_length=255)),
                ('choice_three', models.CharField(max_length=255)),
                ('choice_four', models.CharField(max_length=255)),
                ('correct_ans', models.IntegerField(choices=[(1, 'option 1'), (2, 'option 2'), (3, 'option 3'), (4, 'option 4')], null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_created', to='One.quiz')),
            ],
        ),
    ]
