# Generated by Django 4.2.4 on 2023-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='student_courses',
        ),
        migrations.AddField(
            model_name='quiz',
            name='student_dept',
            field=models.ManyToManyField(default='', help_text='quiz will be sent to this dept students', to='One.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='students_submitted',
            field=models.ManyToManyField(blank=True, related_name='students_submitted', to='One.userprofilestudent'),
        ),
    ]
