# Generated by Django 4.2.4 on 2023-10-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0002_remove_quiz_student_courses_quiz_student_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students_submitted',
        ),
    ]
