# Generated by Django 4.2.4 on 2023-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0003_remove_quiz_students_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='students_submitted',
            field=models.ManyToManyField(blank=True, related_name='students_submitted', to='One.userprofilestudent'),
        ),
    ]
