# Generated by Django 4.2.4 on 2023-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0004_quiz_students_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='students_submitted',
            field=models.ManyToManyField(blank=True, related_name='submitted_quiz', to='One.userprofilestudent'),
        ),
    ]
