# Generated by Django 4.2.4 on 2023-11-08 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0005_alter_quiz_students_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('student_name', models.CharField(max_length=255)),
                ('quiz_name', models.CharField(max_length=255)),
                ('quiz_id', models.UUIDField()),
                ('mark', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='students_submitted',
            field=models.ManyToManyField(blank=True, related_name='students_submitted_quiz', to='One.studentmark'),
        ),
    ]
