# Generated by Django 4.2.4 on 2023-11-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0006_studentmark_alter_quiz_students_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students_submitted',
        ),
    ]
