# Generated by Django 4.2.4 on 2023-11-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0010_quiz_student_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='student_submitted',
        ),
    ]
