# Generated by Django 4.2.4 on 2023-11-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0013_alter_studentmark_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='students_submitted_two',
            field=models.ManyToManyField(blank=True, related_name='students_submitted_quiz_two', to='One.userprofilestudent'),
        ),
    ]
