# Generated by Django 4.2.4 on 2023-11-13 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('One', '0014_quiz_students_submitted_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_educator', to='One.userprofilestudent'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_educator', to='One.userprofileeducator'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofileeducator',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_educator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
