# Generated by Django 4.2.4 on 2023-11-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0015_remove_studentmark_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_quiz_mark', to='One.userprofilestudent'),
        ),
    ]
