# Generated by Django 4.2.4 on 2023-11-14 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0016_alter_studentmark_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students_submitted',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_quiz_attended', to='One.quiz'),
        ),
    ]
