# Generated by Django 4.2.4 on 2023-11-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0017_remove_quiz_students_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='quiz_name',
        ),
    ]
