# Generated by Django 4.2.4 on 2023-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0018_remove_studentmark_quiz_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students_submitted_two',
        ),
        migrations.AddField(
            model_name='quiz',
            name='students_submitted',
            field=models.ManyToManyField(blank=True, related_name='students_submitted_quiz', to='One.userprofilestudent'),
        ),
    ]
