# Generated by Django 4.2.4 on 2023-11-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticator_qrcode', models.ImageField(blank=True, null=True, upload_to='user_authenticator_qrcode_image')),
                ('authenticator_secret_code', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
