# Generated by Django 4.2.4 on 2023-11-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authenticator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_qrcode', to='user.qrcode'),
        ),
    ]
