# Generated by Django 4.2.4 on 2023-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='DOB',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
