# Generated by Django 4.2.4 on 2023-11-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_loginhistory_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='DOB',
            new_name='logged_in',
        ),
    ]
