# Generated by Django 4.2.4 on 2023-11-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_status',
        ),
    ]
