# Generated by Django 4.2.4 on 2023-11-16 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_ticket_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
